# Generated by Django 4.0 on 2021-12-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentgateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='currentBalance',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
    ]
