# Generated by Django 4.0 on 2021-12-28 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentgateway', '0003_paymentstatus_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paymentMethodId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentgateway.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='statusId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentgateway.paymentstatus'),
        ),
    ]
