# Generated by Django 4.0 on 2022-01-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentgateway', '0004_transaction_sum_alter_transaction_paymentmethodid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentstatus',
            old_name='statusCode',
            new_name='id',
        ),
        migrations.AddField(
            model_name='paymentstatus',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='userId',
            field=models.IntegerField(null=True),
        ),
    ]
